### PR TITLE
Add functional UUID detection for Hugo

### PR DESCRIPTION
**Pull request by angstsmurf**
Hugo story files never contain a "UUID://" string, but may contain UUIDs. This code finds them.

### CODE REVIEW

**Comment by erkyrath** [comment]
Can you provide a small Hugo game file with a known IFID for the test directory?

**Comment by angstsmurf** [comment]
The smallest Hugo game file with a UUID-style IFID I can find is [Tales of a Clockwork Boy](https://ifdb.org/viewgame?id=uoyqgvkalgnhzs1n) (63 K). I'm not sure how to write tests, but I can try if you don't have time to do it.

**Comment by erkyrath** [comment]
I was hoping someone could compile a one-room Hugo game with this format.

If I have that, I can write the test.

**Comment by angstsmurf** [comment]
Right, here is a one-room sample game with IFID 39990B7E-B0F2-48FE-818E-C8CA52F2A580. It is  71 K, so I suppose Tales of a Clockwork Boy uses a smaller standard library. I guess it also means that it is possible to make it smaller.

[minimal.hex.zip](https://github.com/iftechfoundation/babel-tool/files/7476585/minimal.hex.zip)

**Comment by erkyrath** [comment]
Thanks. I'll add the test case. 

I'm not worried about the size; it's just easier to not worry about the distribution license on a "real" game.

**Comment by angstsmurf** [comment]
Here is the source of the sample. It is based on the Hugo distribution sample game The Vault of Hugo, with a "constant IFID" added and lots of stuff deleted.
[minimal.hug.txt](https://github.com/iftechfoundation/babel-tool/files/7487932/minimal.hug.txt)

**Comment by angstsmurf** [comment]
To convert the output to uppercase, change line 85 to:
```
UUID_candidate[j] = toupper(hugo_decode(story_file[i+j-8]));
```

**Pull request merged**
